"""added coups table

Revision ID: 064e827cb1dd
Revises: 99545b2e843f
Create Date: 2025-11-03 16:27:58.890656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064e827cb1dd'
down_revision: Union[str, Sequence[str], None] = '99545b2e843f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_statuses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('verification_statuses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_statuses', 'updated_at')
    op.drop_column('verification_statuses', 'created_at')
    # ### end Alembic commands ###
