"""added bill reciept photo

Revision ID: 11b715382a1e
Revises: 7096ad153d78
Create Date: 2025-11-20 14:17:02.010935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b715382a1e'
down_revision: Union[str, Sequence[str], None] = '7096ad153d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('bill_reciept', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issued_statuses', 'bill_reciept')
    # ### end Alembic commands ###
