"""avaliable date in upgrade

Revision ID: 22e01ca16cb8
Revises: 3e6f32497e1a
Create Date: 2025-12-26 11:57:22.316299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22e01ca16cb8"
down_revision: Union[str, Sequence[str], None] = "3e6f32497e1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upgrade_requests", sa.Column("scheduled_at", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upgrade_requests", "scheduled_at")
    # ### end Alembic commands ###
