"""added vendor info and cleaned teh tables

Revision ID: 38516ad5f22f
Revises: b6329588c269
Create Date: 2025-11-07 15:44:11.216203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38516ad5f22f'
down_revision: Union[str, Sequence[str], None] = 'b6329588c269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('vendor_name', sa.String(length=222), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('vendor_spoc',
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=222), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_spoc_id'), 'vendor_spoc', ['id'], unique=False)
    op.add_column('candidates', sa.Column('coupon_code', sa.String(length=15), nullable=True))
    op.add_column('candidates', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('vendor_id', sa.String(length=40), nullable=True))
    op.alter_column('candidates', 'full_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('candidates', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('candidates', 'mobile_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('candidates', 'store_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('candidates', 'is_candidate_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_index('ix_candidates_coupon', 'candidates', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_candidates_coupon_code'), 'candidates', ['coupon_code'], unique=True)
    op.create_foreign_key(None, 'candidates', 'vendor_spoc', ['vendor_id'], ['id'], ondelete='set null')
    op.drop_column('candidates', 'dob')
    op.drop_column('candidates', 'city')
    op.drop_column('candidates', 'parent_relation')
    op.drop_column('candidates', 'disability_type')
    op.drop_column('candidates', 'photo_url')
    op.drop_column('candidates', 'parent_email')
    op.drop_column('candidates', 'aadhar_last_four_digits')
    op.drop_column('candidates', 'state')
    op.drop_column('candidates', 'parent_mobile_number')
    op.drop_column('candidates', 'parent_employee_code')
    op.drop_column('candidates', 'parent_photo_url')
    op.drop_column('candidates', 'parent_name')
    op.add_column('issued_statuses', sa.Column('evidence_photo', sa.Text(), nullable=True))
    op.drop_column('issued_statuses', 'updated_at')
    op.drop_column('issued_statuses', 'issued_photo')
    op.drop_column('stores', 'city')
    op.drop_column('stores', 'maps_link')
    op.drop_column('stores', 'state')
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('verification_statuses', sa.Column('otp_verified_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('verification_statuses', sa.Column('facial_verified_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('verification_statuses', 'is_coupon_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_statuses', sa.Column('is_coupon_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('verification_statuses', 'facial_verified_at')
    op.drop_column('verification_statuses', 'otp_verified_at')
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('stores', sa.Column('state', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('stores', sa.Column('maps_link', mysql.TEXT(), nullable=True))
    op.add_column('stores', sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('issued_statuses', sa.Column('issued_photo', mysql.TEXT(), nullable=True))
    op.add_column('issued_statuses', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.drop_column('issued_statuses', 'evidence_photo')
    op.add_column('candidates', sa.Column('parent_name', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('candidates', sa.Column('parent_photo_url', mysql.TEXT(), nullable=True))
    op.add_column('candidates', sa.Column('parent_employee_code', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('candidates', sa.Column('parent_mobile_number', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('candidates', sa.Column('state', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('candidates', sa.Column('aadhar_last_four_digits', mysql.VARCHAR(length=5), nullable=False))
    op.add_column('candidates', sa.Column('parent_email', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('candidates', sa.Column('photo_url', mysql.TEXT(), nullable=True))
    op.add_column('candidates', sa.Column('disability_type', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('candidates', sa.Column('parent_relation', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('candidates', sa.Column('city', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('candidates', sa.Column('dob', sa.DATE(), nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_coupon_code'), table_name='candidates')
    op.drop_index('ix_candidates_coupon', table_name='candidates')
    op.alter_column('candidates', 'is_candidate_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('candidates', 'store_id',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('candidates', 'mobile_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.alter_column('candidates', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('candidates', 'full_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_column('candidates', 'vendor_id')
    op.drop_column('candidates', 'photo')
    op.drop_column('candidates', 'coupon_code')
    op.drop_index(op.f('ix_vendor_spoc_id'), table_name='vendor_spoc')
    op.drop_table('vendor_spoc')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
