"""added fields to upgrade requests.

Revision ID: 387c98795e30
Revises: 
Create Date: 2025-12-10 14:51:24.857711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '387c98795e30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('is_requested_to_upgrade', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('upgrade_requests', sa.Column('cost_of_upgrade', sa.Integer(), nullable=False))
    op.add_column('upgrade_requests', sa.Column('new_laptop_serial', sa.String(length=100), nullable=True))
    op.alter_column('upgrade_requests', 'upgrade_product_info',
               existing_type=mysql.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('upgrade_requests', 'upgrade_reason',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('upgrade_requests', 'upgrade_product_type',
               existing_type=mysql.VARCHAR(length=122),
               nullable=True)
    op.drop_column('upgrade_requests', 'payment_difference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade_requests', sa.Column('payment_difference', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('upgrade_requests', 'upgrade_product_type',
               existing_type=mysql.VARCHAR(length=122),
               nullable=False)
    op.alter_column('upgrade_requests', 'upgrade_reason',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('upgrade_requests', 'upgrade_product_info',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=600),
               existing_nullable=True)
    op.drop_column('upgrade_requests', 'new_laptop_serial')
    op.drop_column('upgrade_requests', 'cost_of_upgrade')
    op.drop_column('issued_statuses', 'is_requested_to_upgrade')
    # ### end Alembic commands ###
