"""changed fields according to the data

Revision ID: 3c0c361da2ed
Revises: 7d1673ccdb2c
Create Date: 2025-11-28 09:53:30.666927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c0c361da2ed'
down_revision: Union[str, Sequence[str], None] = '7d1673ccdb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['mobile_number'])
    op.drop_column('users', 'username')
    op.add_column('vendors', sa.Column('vendor_owner', sa.Text(), nullable=True))
    op.drop_column('vendors', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('location', mysql.TEXT(), nullable=True))
    op.drop_column('vendors', 'vendor_owner')
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'mobile_number')
    # ### end Alembic commands ###
