"""utility file uploads

Revision ID: 3e6f32497e1a
Revises: af543d825f4d
Create Date: 2025-12-22 23:32:36.186306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6f32497e1a'
down_revision: Union[str, Sequence[str], None] = 'af543d825f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_files',
    sa.Column('type', sa.String(length=222), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'path', name='uq_utility_files_type_path')
    )
    op.create_index(op.f('ix_utility_files_id'), 'utility_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_files_id'), table_name='utility_files')
    op.drop_table('utility_files')
    # ### end Alembic commands ###
