"""cascades on updates for foriegn keys

Revision ID: 49fa2fb566b9
Revises: c1a07aeea013
Create Date: 2025-12-01 12:07:13.210519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fa2fb566b9'
down_revision: Union[str, Sequence[str], None] = 'c1a07aeea013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bulk_upload_errors_ibfk_1'), 'bulk_upload_errors', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_upload_errors', 'bulk_upload_results', ['upload_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('bulk_upload_results_ibfk_1'), 'bulk_upload_results', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_upload_results', 'stores', ['store_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('candidates_ibfk_1'), 'candidates', type_='foreignkey')
    op.drop_constraint(op.f('candidates_ibfk_2'), 'candidates', type_='foreignkey')
    op.drop_constraint(op.f('candidates_ibfk_3'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['verified_by'], ['id'], onupdate='cascade', ondelete='set null')
    op.create_foreign_key(None, 'candidates', 'stores', ['store_id'], ['id'], onupdate='cascade')
    op.create_foreign_key(None, 'candidates', 'vendor_spoc', ['vendor_spoc_id'], ['id'], onupdate='cascade', ondelete='set null')
    op.drop_constraint(op.f('coupons_ibfk_1'), 'coupons', type_='foreignkey')
    op.create_foreign_key(None, 'coupons', 'candidates', ['candidate_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('issued_statuses_ibfk_2'), 'issued_statuses', type_='foreignkey')
    op.drop_constraint(op.f('issued_statuses_ibfk_1'), 'issued_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'issued_statuses', 'candidates', ['candidate_id'], ['id'], onupdate='cascade')
    op.create_foreign_key(None, 'issued_statuses', 'users', ['issued_by'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('otps_ibfk_1'), 'otps', type_='foreignkey')
    op.create_foreign_key(None, 'otps', 'candidates', ['candidate_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('password_reset_otps_ibfk_1'), 'password_reset_otps', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_otps', 'users', ['user_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'], onupdate='cascade', ondelete='set null')
    op.drop_constraint(op.f('vendor_spoc_ibfk_1'), 'vendor_spoc', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_spoc', 'vendors', ['vendor_id'], ['id'], onupdate='cascade')
    op.drop_constraint(op.f('verification_statuses_ibfk_1'), 'verification_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'verification_statuses', 'candidates', ['candidate_id'], ['id'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_statuses', type_='foreignkey')
    op.create_foreign_key(op.f('verification_statuses_ibfk_1'), 'verification_statuses', 'candidates', ['candidate_id'], ['id'])
    op.drop_constraint(None, 'vendor_spoc', type_='foreignkey')
    op.create_foreign_key(op.f('vendor_spoc_ibfk_1'), 'vendor_spoc', 'vendors', ['vendor_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'password_reset_otps', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_otps_ibfk_1'), 'password_reset_otps', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.create_foreign_key(op.f('otps_ibfk_1'), 'otps', 'candidates', ['candidate_id'], ['id'])
    op.drop_constraint(None, 'issued_statuses', type_='foreignkey')
    op.drop_constraint(None, 'issued_statuses', type_='foreignkey')
    op.create_foreign_key(op.f('issued_statuses_ibfk_1'), 'issued_statuses', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('issued_statuses_ibfk_2'), 'issued_statuses', 'users', ['issued_by'], ['id'])
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.create_foreign_key(op.f('coupons_ibfk_1'), 'coupons', 'candidates', ['candidate_id'], ['id'])
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_ibfk_3'), 'candidates', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('candidates_ibfk_2'), 'candidates', 'vendor_spoc', ['vendor_spoc_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('candidates_ibfk_1'), 'candidates', 'stores', ['store_id'], ['id'])
    op.drop_constraint(None, 'bulk_upload_results', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_upload_results_ibfk_1'), 'bulk_upload_results', 'stores', ['store_id'], ['id'])
    op.drop_constraint(None, 'bulk_upload_errors', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_upload_errors_ibfk_1'), 'bulk_upload_errors', 'bulk_upload_results', ['upload_id'], ['id'])
    # ### end Alembic commands ###
