"""added regions

Revision ID: 4c1c460b16bd
Revises: 22e01ca16cb8
Create Date: 2026-01-04 22:00:47.346125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1c460b16bd'
down_revision: Union[str, Sequence[str], None] = '22e01ca16cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('region_user_associations',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'region_id')
    )
    op.add_column('candidates', sa.Column('region_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'candidates', 'regions', ['region_id'], ['id'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'region_id')
    op.drop_table('region_user_associations')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
