"""increase in division name sie

Revision ID: 54ad56f9397c
Revises: 49fa2fb566b9
Create Date: 2025-12-02 11:59:02.482514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54ad56f9397c'
down_revision: Union[str, Sequence[str], None] = '49fa2fb566b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'division',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=555),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'division',
               existing_type=sa.String(length=555),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
