"""onupdate caascade for city association

Revision ID: 5bb9092d4f98
Revises: e73d9d3c6e25
Create Date: 2026-01-08 09:54:33.138933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb9092d4f98'
down_revision: Union[str, Sequence[str], None] = 'e73d9d3c6e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('store_city_associations_ibfk_2'), 'store_city_associations', type_='foreignkey')
    op.drop_constraint(op.f('store_city_associations_ibfk_1'), 'store_city_associations', type_='foreignkey')
    op.create_foreign_key(None, 'store_city_associations', 'stores', ['store_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'store_city_associations', 'cities', ['city_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_city_associations', type_='foreignkey')
    op.drop_constraint(None, 'store_city_associations', type_='foreignkey')
    op.create_foreign_key(op.f('store_city_associations_ibfk_1'), 'store_city_associations', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('store_city_associations_ibfk_2'), 'store_city_associations', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
