"""store cities

Revision ID: 679242983f57
Revises: 4c1c460b16bd
Create Date: 2026-01-05 11:55:14.844410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '679242983f57'
down_revision: Union[str, Sequence[str], None] = '4c1c460b16bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('store_city_associations',
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('store_id', 'city_id')
    )
    op.drop_index(op.f('uq_stores_name_city'), table_name='stores')
    op.drop_column('stores', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('uq_stores_name_city'), 'stores', ['name', 'city'], unique=True)
    op.drop_table('store_city_associations')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
