"""initial

Revision ID: 7096ad153d78
Revises: 
Create Date: 2025-11-20 14:03:39.603408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7096ad153d78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issued_statuses_user'), 'issued_statuses', type_='foreignkey')
    op.create_foreign_key(None, 'issued_statuses', 'users', ['issued_by'], ['id'])
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.drop_constraint(None, 'issued_statuses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issued_statuses_user'), 'issued_statuses', 'users', ['issued_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
