"""added store employee details for evidence collection

Revision ID: 7d1673ccdb2c
Revises: a4e175e47384
Create Date: 2025-11-27 11:56:17.249375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7d1673ccdb2c'
down_revision: Union[str, Sequence[str], None] = 'a4e175e47384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('store_employee_name', sa.String(length=150), nullable=True))
    op.add_column('issued_statuses', sa.Column('store_employee_mobile', sa.String(length=15), nullable=True))
    op.add_column('issued_statuses', sa.Column('store_employee_photo', sa.Text(), nullable=True))
    op.drop_column('issued_statuses', 'digital_signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('digital_signature', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('issued_statuses', 'store_employee_photo')
    op.drop_column('issued_statuses', 'store_employee_mobile')
    op.drop_column('issued_statuses', 'store_employee_name')
    # ### end Alembic commands ###
