"""added verification statuses

Revision ID: 7e71d4f493d3
Revises: b5563ad8c2f0
Create Date: 2025-11-03 10:16:30.967303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e71d4f493d3'
down_revision: Union[str, Sequence[str], None] = 'b5563ad8c2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_statuses',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('is_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('is_facial_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.alter_column('stores', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_table('verification_statuses')
    # ### end Alembic commands ###
