"""tracking offline reports and status of laptop issuance and

Revision ID: 7f6c54f39541
Revises: 3c0c361da2ed
Create Date: 2025-11-28 12:05:56.880360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f6c54f39541"
down_revision: Union[str, Sequence[str], None] = "3c0c361da2ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_upload_results",
        sa.Column("store_id", sa.String(length=40), nullable=False),
        sa.Column("file_path", sa.String(length=199), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("successful_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bulk_upload_results_id"), "bulk_upload_results", ["id"], unique=False
    )
    op.create_table(
        "bulk_upload_errors",
        sa.Column("upload_id", sa.String(length=40), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("beneficiary_employee_id", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("voucher_code", sa.String(length=15), nullable=True),
        sa.Column("laptop_serial", sa.String(length=40), nullable=True),
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["bulk_upload_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bulk_upload_errors_id"), "bulk_upload_errors", ["id"], unique=False
    )
    op.add_column(
        "issued_statuses",
        sa.Column(
            "is_offline", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issued_statuses", "is_offline")
    op.drop_index(op.f("ix_bulk_upload_errors_id"), table_name="bulk_upload_errors")
    op.drop_table("bulk_upload_errors")
    op.drop_index(op.f("ix_bulk_upload_results_id"), table_name="bulk_upload_results")
    op.drop_table("bulk_upload_results")
    # ### end Alembic commands ###
