"""added parent fields

Revision ID: 99545b2e843f
Revises: cc69e53d5ff4
Create Date: 2025-11-03 13:49:05.629368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99545b2e843f'
down_revision: Union[str, Sequence[str], None] = 'cc69e53d5ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('parent_name', sa.String(length=256), nullable=True))
    op.add_column('candidates', sa.Column('parent_employee_code', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('parent_mobile_number', sa.String(length=15), nullable=True))
    op.add_column('candidates', sa.Column('parent_email', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('parent_relation', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('parent_photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'parent_photo_url')
    op.drop_column('candidates', 'parent_relation')
    op.drop_column('candidates', 'parent_email')
    op.drop_column('candidates', 'parent_mobile_number')
    op.drop_column('candidates', 'parent_employee_code')
    op.drop_column('candidates', 'parent_name')
    # ### end Alembic commands ###
