"""added uploaded evidences in verification_statuses

Revision ID: a4e175e47384
Revises: bff81ca3ec8b
Create Date: 2025-11-27 09:22:58.551852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4e175e47384'
down_revision: Union[str, Sequence[str], None] = 'bff81ca3ec8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_statuses', sa.Column('uploaded_candidate_photo', sa.Text(), nullable=True))
    op.add_column('verification_statuses', sa.Column('entered_aadhar_number', sa.String(length=20), nullable=True))
    op.drop_column('verification_statuses', 'candidate_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_statuses', sa.Column('candidate_photo', mysql.TEXT(), nullable=True))
    op.drop_column('verification_statuses', 'entered_aadhar_number')
    op.drop_column('verification_statuses', 'uploaded_candidate_photo')
    # ### end Alembic commands ###
