"""contact to mobile and email

Revision ID: ac2e4bf19aba
Revises: ec7074280fcb
Create Date: 2025-11-25 13:44:10.632108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac2e4bf19aba'
down_revision: Union[str, Sequence[str], None] = 'ec7074280fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_spoc', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('vendor_spoc', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_column('vendor_spoc', 'contact')
    op.add_column('vendors', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.add_column('vendors', sa.Column('email', sa.String(length=64), nullable=True))
    op.drop_column('vendors', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('contact', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('vendors', 'email')
    op.drop_column('vendors', 'mobile_number')
    op.add_column('vendor_spoc', sa.Column('contact', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('vendor_spoc', 'email')
    op.drop_column('vendor_spoc', 'mobile_number')
    # ### end Alembic commands ###
