"""new

Revision ID: af543d825f4d
Revises: 387c98795e30
Create Date: 2025-12-15 10:02:32.423210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af543d825f4d'
down_revision: Union[str, Sequence[str], None] = '387c98795e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('aadhar_number_hashed', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('aadhar_number_masked', sa.String(length=36), nullable=True))
    op.drop_column('candidates', 'aadhar_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('aadhar_number', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('candidates', 'aadhar_number_masked')
    op.drop_column('candidates', 'aadhar_number_hashed')
    # ### end Alembic commands ###
