"""added laptop serial to issued statuses

Revision ID: b6329588c269
Revises: d4a70a8d9088
Create Date: 2025-11-04 16:40:46.469289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6329588c269'
down_revision: Union[str, Sequence[str], None] = 'd4a70a8d9088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('issued_laptop_serial', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'issued_statuses', ['issued_laptop_serial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issued_statuses', type_='unique')
    op.drop_column('issued_statuses', 'issued_laptop_serial')
    # ### end Alembic commands ###
