"""made changes to store_data

Revision ID: c1a07aeea013
Revises: 7f6c54f39541
Create Date: 2025-12-01 10:02:29.708321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1a07aeea013'
down_revision: Union[str, Sequence[str], None] = '7f6c54f39541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('stores', 'address',
               existing_type=mysql.VARCHAR(length=600),
               nullable=True)
    op.drop_index(op.f('uq_stores_name_address'), table_name='stores')
    op.create_unique_constraint('uq_stores_name_city', 'stores', ['name', 'city'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stores_name_city', 'stores', type_='unique')
    op.create_index(op.f('uq_stores_name_address'), 'stores', ['name', 'address'], unique=True)
    op.alter_column('stores', 'address',
               existing_type=mysql.VARCHAR(length=600),
               nullable=False)
    op.drop_column('stores', 'count')
    # ### end Alembic commands ###
