"""upgrade req table

Revision ID: c225f3f82db2
Revises: 9e2e789b5646
Create Date: 2025-12-09 15:20:05.316708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c225f3f82db2'
down_revision: Union[str, Sequence[str], None] = '9e2e789b5646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upgrade_requests', sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upgrade_requests', 'is_accepted')
    # ### end Alembic commands ###
