"""Make Otp.expires_at timezone aware

Revision ID: cc69e53d5ff4
Revises: 7e71d4f493d3
Create Date: 2025-11-03 11:51:32.606307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc69e53d5ff4'
down_revision: Union[str, Sequence[str], None] = '7e71d4f493d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'expires_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'expires_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
