"""added coupon verificatio step

Revision ID: d4a70a8d9088
Revises: b4cbfcdcdac9
Create Date: 2025-11-04 11:20:14.106144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a70a8d9088'
down_revision: Union[str, Sequence[str], None] = 'b4cbfcdcdac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_statuses', sa.Column('is_coupon_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_statuses', 'is_coupon_verified')
    # ### end Alembic commands ###
