"""increase size in vendor mobile

Revision ID: e56a3e45aaa3
Revises: 54ad56f9397c
Create Date: 2025-12-03 10:03:11.857848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e56a3e45aaa3'
down_revision: Union[str, Sequence[str], None] = '54ad56f9397c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_spoc', 'mobile_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_spoc', 'mobile_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
