"""issued at

Revision ID: e73d9d3c6e25
Revises: 679242983f57
Create Date: 2026-01-07 10:24:12.034507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73d9d3c6e25'
down_revision: Union[str, Sequence[str], None] = '679242983f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('voucher_issued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'voucher_issued_at')
    # ### end Alembic commands ###
