"""changed id fields in candidates and stores

Revision ID: ee6540c71757
Revises: 9e9f2d440a3c
Create Date: 2025-10-30 16:33:07.921964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee6540c71757'
down_revision: Union[str, Sequence[str], None] = '9e9f2d440a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('aadhar_last_four_digits', sa.String(length=5), nullable=False))
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_column('candidates', 'candidate_id')
    op.drop_index(op.f('ix_store_store_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_column('stores', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('store_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=True)
    op.create_index(op.f('ix_store_store_id'), 'stores', ['store_id'], unique=False)
    op.add_column('candidates', sa.Column('candidate_id', mysql.VARCHAR(length=30), nullable=False))
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.drop_column('candidates', 'aadhar_last_four_digits')
    # ### end Alembic commands ###
