"""consolidate verification

Revision ID: feff80024480
Revises: ac2e4bf19aba
Create Date: 2025-11-26 11:41:08.659097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feff80024480'
down_revision: Union[str, Sequence[str], None] = 'ac2e4bf19aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_statuses', sa.Column('digital_signature', sa.String(length=150), nullable=True))
    op.add_column('verification_statuses', sa.Column('is_coupon_verified', sa.Boolean(), nullable=False))
    op.add_column('verification_statuses', sa.Column('is_aadhar_verified', sa.Boolean(), nullable=False))
    op.add_column('verification_statuses', sa.Column('candidate_photo', sa.Text(), nullable=True))
    op.add_column('verification_statuses', sa.Column('overriding_user', sa.String(length=150), nullable=True))
    op.add_column('verification_statuses', sa.Column('overriding_reason', sa.Text(), nullable=True))
    op.add_column('verification_statuses', sa.Column('coupon_verified_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('verification_statuses', sa.Column('aadhar_verified_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_statuses', 'aadhar_verified_at')
    op.drop_column('verification_statuses', 'coupon_verified_at')
    op.drop_column('verification_statuses', 'overriding_reason')
    op.drop_column('verification_statuses', 'overriding_user')
    op.drop_column('verification_statuses', 'candidate_photo')
    op.drop_column('verification_statuses', 'is_aadhar_verified')
    op.drop_column('verification_statuses', 'is_coupon_verified')
    op.drop_column('issued_statuses', 'digital_signature')
    # ### end Alembic commands ###
